// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwwIhTQoKDOdyFNvYtIT08ITfdI77OCGQ',
    appId: '1:998872104843:web:7d0a979a068c8468cd398e',
    messagingSenderId: '998872104843',
    projectId: 'mr-yummy-v2',
    authDomain: 'mr-yummy-v2.firebaseapp.com',
    storageBucket: 'mr-yummy-v2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmH5Yi-oT0Y8SYyn9UhdplRI5SczS_5d0',
    appId: '1:998872104843:android:ba010ce76f62b4c2cd398e',
    messagingSenderId: '998872104843',
    projectId: 'mr-yummy-v2',
    storageBucket: 'mr-yummy-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQqQJslG6UDpIEVdhH6V4W8S7eAxNNdo4',
    appId: '1:998872104843:ios:ab2a1bc591c5cafbcd398e',
    messagingSenderId: '998872104843',
    projectId: 'mr-yummy-v2',
    storageBucket: 'mr-yummy-v2.appspot.com',
    iosClientId: '998872104843-q57uuesd7qus93rc7n6iubdaucde6buh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrYummyV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQqQJslG6UDpIEVdhH6V4W8S7eAxNNdo4',
    appId: '1:998872104843:ios:ab2a1bc591c5cafbcd398e',
    messagingSenderId: '998872104843',
    projectId: 'mr-yummy-v2',
    storageBucket: 'mr-yummy-v2.appspot.com',
    iosClientId: '998872104843-q57uuesd7qus93rc7n6iubdaucde6buh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrYummyV2',
  );
}
